drop table Article if exists;
drop table Member if exists;
drop table MemberRole if exists;
create table Article (
	articleNo integer generated by default as identity (start with 1), 
	content varchar(255), 
	title varchar(255), 
	memberId varchar(20), 
	primary key (articleNo)
);
create table Member (
	id varchar(20) not null, 
	name varchar(40) not null, 
	password varchar(20) not null, 
	primary key (id)
);
create table MemberRole (
	seq integer generated by default as identity (start with 1), 
	role varchar(50) not null, 
	memberId varchar(20), 
	primary key (seq)
);
--alter table Article add constraint FK_a51cfc94891342578f1244f4a07 foreign key (memberId) references Member;
--alter table MemberRole add constraint UK_9a2dc11c9c874865906b116fa56 unique (memberId, role);
--alter table MemberRole add constraint FK_7c24a5343cb143fc9b2076a4e55 foreign key (memberId) references Member;