
drop table Article if exists;
drop table customer if exists;

create table customer (
	SEQ integer generated by default as identity (start with 1),
	ID varchar(255), 
	PASSWORD varchar(255), 
	NAME varchar(255), 
	primary key (SEQ)
);

create table Article (
	articleNo integer not null, 
	content varchar(255), 
	memberSeq integer, 
	title varchar(255), 
	primary key (articleNo)
);